
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - app
      - recommendation
      - ocr

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
      - recommendation
      - ocr

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  recommendation:
    build:
      context: ./recommendation_pipeline
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  ocr:
    build:
      context: ./OCR
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

volumes:
  postgres_data:
